export async function verifyAnalytics({page,api,check,nav,close,out,fs}){
  const capture=async(file)=>{while(await page.getByRole('button',{name:'Dismiss notification',exact:true}).count())await page.getByRole('button',{name:'Dismiss notification',exact:true}).first().click();await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:out+file,fullPage:true});};
  const bid=await page.evaluate(()=>S.bid),initial=await api('state?business='+bid),day=initial.today;
  const before=await page.evaluate(day=>addDays(day,-10),day),late=await page.evaluate(day=>addDays(day,-1),day);
  const client=await api('record',{business_id:bid,kind:'customers',data:{name:'Precision Fleet · Fictional',phone:'9800000091'}});
  const employee=await api('record',{business_id:bid,kind:'employees',data:{name:'Asha · Fictional technician',role:'Paint technician',hourly_cost:100}});
  const job=await api('record',{business_id:bid,kind:'jobs',data:{name:'Fleet panel restoration',customer_id:client.id,date:before,due_date:day,stage:initial.stages.at(-1),employee_ids:[employee.id],labor_cost:250,costs_final:true,tasks:[]}});
  const bad=await api('record',{business_id:bid,kind:'jobs',data:{name:'Scope overrun to review',customer_id:client.id,date:before,due_date:late,stage:initial.stages.at(-1),employee_ids:[employee.id],labor_cost:500,costs_final:true,tasks:[]}});
  const issue=async(name,price,cost,jid)=>{let invoice=await api('record',{business_id:bid,kind:'invoices',data:{customer_id:client.id,job_id:jid,date:day,due_date:late,vat_mode:'none',items:[{description:name,qty:1,rate:price,unit_cost:cost,category:'Service'}]}});return api('action',{business_id:bid,kind:'invoices',id:invoice.id,version:invoice.version,action:'issue'});};
  const invoice=await issue('Panel restoration package',1200,200,job.id);await issue('Underquoted repair package',300,600,bad.id);
  await api('record',{business_id:bid,kind:'payments',data:{invoice_id:invoice.id,date:day,amount:300,method:'Cash'}});
  await api('record',{business_id:bid,kind:'expenses',data:{name:'Recorded operating supplies',date:day,amount:80,category:'Office',expense_treatment:'Operating expense'}});
  await api('record',{business_id:bid,kind:'expenses',data:{name:'Owner withdrawal for review',date:day,amount:40,category:'Other',expense_treatment:'Owner withdrawal'}});
  await page.locator('[data-action=refresh]').click();await page.waitForFunction(id=>S.state.records.jobs.some(x=>x.id===id),job.id);
  await nav('reports');await page.getByRole('heading',{name:'Sales and operating result',exact:true}).waitFor();
  let report=await api('analytics?business='+bid);check(report.business_name===initial.business.trading_name,'Analytics lost own trading name');
  check(report.highlights.services.highest.name==='Panel restoration package'&&report.highlights.services.lowest.name==='Underquoted repair package','Service highlights do not reflect saved costs');
  check(report.recommendations.some(x=>x.id==='job-loss'&&x.record_id===bad.id),'Job loss has no actionable source');
  check(await page.getByRole('heading',{name:'Strongest results and areas to review',exact:true}).count()===1,'Best/worst panel is missing');
  await capture('/analytics-overview-desktop.png');
  await page.getByRole('tab',{name:'Profit & loss',exact:true}).click();await page.getByRole('heading',{name:'Recorded profit & loss',exact:true}).waitFor();
  const result=await page.locator('.summary-line.grand').first().textContent();check(result.includes(Number(report.summary.operating_result).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})),'Profit UI does not match database-backed result');
  check((await page.locator('#business-analytics-panel').textContent()).includes('Owner withdrawal'),'Cash expense exclusions missing');
  await capture('/analytics-profit-desktop.png');
  const downloadEvent=page.waitForEvent('download');await page.getByRole('button',{name:'Export analysis',exact:true}).click();const download=await downloadEvent;await download.saveAs(out+'/analytics-export.csv');
  const csv=await fs.readFile(out+'/analytics-export.csv','utf8');check(csv.includes('Precision Fleet')&&csv.includes('operating_result')&&csv.includes('Basis'),'Export lacks source metrics and calculation basis');
  await page.getByRole('tab',{name:'Work & services',exact:true}).click();
  await page.locator('tr').filter({hasText:'Fleet panel restoration'}).getByRole('button',{name:'Quality review',exact:true}).click();
  await page.getByLabel('Actual completion date, AD').fill(day);await page.getByLabel('Client quality rating (0 = not recorded)').selectOption('5');
  await page.getByLabel('Recorded rework events').fill('1');await page.getByLabel('Review notes / evidence').fill('Client confirmed the finish and handover. Fictional evidence.');
  await page.getByRole('button',{name:'Save quality review',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('#editor').open);
  let state=await api('state?business='+bid);const reviewed=state.records.jobs.find(x=>x.id===job.id);check(reviewed.completion_date===day&&reviewed.quality_rating===5&&reviewed.rework_count===1,'Quality review was not saved');
  await page.getByRole('tab',{name:'Team',exact:true}).click();await page.getByRole('heading',{name:'Team performance from recorded work',exact:true}).waitFor();
  report=await api('analytics?business='+bid);const team=report.team.find(x=>x.id===employee.id);check(team.reviewed===1&&team.on_time_percent===100&&team.quality_rating===5&&team.reworks===1,'Team metrics do not use saved owner review');
  check((await page.locator('tr').filter({hasText:employee.name}).textContent()).includes('1 reviewed assignments'),'Team delivery sample hidden');
  await capture('/analytics-team-desktop.png');
  await page.getByRole('tab',{name:'Clients',exact:true}).click();await page.getByLabel('Find a client').fill('Precision');
  check(await page.locator('#analysis-client-rows tr').count()===1,'Client analysis search does not filter');await page.getByLabel('Sort this list').selectOption('overdue');
  check((await page.locator('#analysis-client-rows').textContent()).includes('1,200.00'),'Client outstanding amount incorrect');await capture('/analytics-clients-desktop.png');
  await page.getByRole('tab',{name:'Patterns',exact:true}).click();check(await page.getByRole('heading',{name:'Sales by weekday',exact:true}).count()===1,'Weekday patterns missing');
  await page.getByRole('tab',{name:'Next actions',exact:true}).click();
  const recommendation=page.locator('.analysis-advice').filter({hasText:'Review the lowest job contribution'});await recommendation.getByRole('button',{name:'Review source',exact:true}).click();
  check((await page.locator('#editor').textContent()).includes('Scope overrun to review'),'Loss action opens wrong record');await close();
  await recommendation.getByRole('button',{name:'Plan an action',exact:true}).click();await page.locator('#field-notes').fill('Owner will review scope changes and material costing. Fictional test.');
  await page.locator('[form=record-form][type=submit]').click();await page.waitForFunction(()=>!document.querySelector('#editor').open);
  state=await api('state?business='+bid);check(state.records.followups.some(x=>x.name==='Review the lowest job contribution'&&x.task_category==='work'&&x.notes.includes('scope changes')),'Recommended action was not saved as follow-up');
  await page.getByRole('button',{name:'Last 90 days',exact:true}).click();await page.waitForFunction(()=>S.analyticsCache?.data.period.days===90);
  check(await page.locator('#analytics-period input[name=start]').inputValue()===await page.evaluate(()=>S.reportStart),'Date preset UI/state mismatch');
  await page.getByRole('button',{name:'This month',exact:true}).click();await page.waitForFunction(()=>S.analyticsCache?.data.period.start===S.state.today.slice(0,8)+'01');
  await page.route('**/api/analytics?**',route=>route.abort());await page.getByRole('button',{name:'Refresh',exact:true}).last().click();
  await page.getByRole('button',{name:'Try again',exact:true}).waitFor();check(await page.getByText('Analysis could not load',{exact:true}).count()===1,'Failed analysis did not provide recovery');
  await page.unroute('**/api/analytics?**');await page.getByRole('button',{name:'Try again',exact:true}).click();await page.locator('.analysis-advice').first().waitFor();
  for(const width of [320,390,768,900,901]){
    await page.setViewportSize({width,height:844});await page.getByRole('tab',{name:'Overview',exact:true}).click();await page.locator('.analytics-trend').waitFor();
    check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Analytics overview overflows at '+width);
    if(width===390)await capture('/analytics-overview-phone.png');
    await page.getByRole('tab',{name:'Team',exact:true}).click();check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Analytics table overflows document at '+width);
    if(width===390)await capture('/analytics-team-phone.png');
  }
  await page.setViewportSize({width:1440,height:1100});await page.getByRole('tab',{name:'Overview',exact:true}).click();
  await page.getByRole('tab',{name:'Overview',exact:true}).focus();await page.keyboard.press('ArrowRight');await page.getByRole('heading',{name:'Recorded profit & loss',exact:true}).waitFor();check(await page.getByRole('tab',{name:'Profit & loss',exact:true}).getAttribute('aria-selected')==='true','Keyboard tab navigation failed');
  // Browser-only email form transport fixtures. Real provider-to-Postgres sessions are tested in test_cloud.py.
  const health=await api('health');await page.getByRole('button',{name:'Sign out',exact:true}).click();
  await page.route('**/api/health',route=>route.fulfill({json:{...health,user:null,csrf:null,cloud:true,email_auth:true,registration_enabled:true,setup_required:false}}));
  await page.reload();await page.getByLabel('Email address',{exact:true}).waitFor();await page.getByRole('button',{name:'Create your business account',exact:true}).click();
  await page.getByLabel('Your name',{exact:true}).fill('Fictional Email Owner');await page.getByLabel('Email address',{exact:true}).fill('browser@example.test');
  let sent=0;await page.route('**/api/email-code',route=>{sent++;return route.fulfill({json:{message:'Fictional code sent. Check email.'}});});
  await page.getByRole('button',{name:'Send sign-in code',exact:true}).click();await page.getByLabel('Code from your email').waitFor();
  check(sent===1&&await page.getByRole('button',{name:/Resend/}).isDisabled(),'Email code cooldown or initial request failed');
  await page.route('**/api/email-login',route=>route.fulfill({status:401,json:{error:'Fictional invalid code. Request a fresh code.'}}));
  await page.getByLabel('Code from your email').fill('123456');await page.getByRole('button',{name:'Verify and open workspace',exact:true}).click();
  await page.getByRole('alert').filter({hasText:'Fictional invalid code'}).waitFor();check(await page.getByLabel('Code from your email').count()===1,'Invalid email code destroyed sign-in form');
  await page.getByRole('button',{name:'Change email',exact:true}).click();check(!await page.getByLabel('Email address',{exact:true}).evaluate(x=>x.readOnly),'Change email leaves read-only address');
  await capture('/verified-email-signup-desktop.png');
  await page.setViewportSize({width:390,height:844});check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Verified email sign-in overflows phone');await capture('/verified-email-signup-phone.png');
  await page.getByRole('button',{name:'Use a username and password',exact:true}).click();check(await page.getByLabel('Username',{exact:true}).count()===1,'Legacy sign-in missing from email mode');
  await page.getByRole('button',{name:'Use verified email',exact:true}).click();check(await page.getByLabel('Email address',{exact:true}).count()===1,'Cannot return to verified email sign-in');
  await page.unroute('**/api/health');await page.unroute('**/api/email-code');await page.unroute('**/api/email-login');
}
