export async function verifyExperience({page,api,check,nav,close,formSave,out,fs}){
  await page.setViewportSize({width:1440,height:1100});
  async function createBusiness(profile,name,country='NP'){
    await nav('settings');await page.getByRole('button',{name:'+ Add another business'}).click();
    await page.locator(`[data-profile-choice="${profile}"]`).click();
    await page.locator('#setup-country').selectOption(country);
    await page.getByLabel('Business name',{exact:true}).fill(name);
    await page.getByLabel('Address',{exact:true}).fill(country==='IN'?'Test Road, Pune':'Test Road, Kathmandu');
    if(country==='IN'){
      await page.locator('#field-state_code').selectOption('27');
      await page.locator('#field-gst_registration').selectOption('regular');
      await page.locator('#field-gstin').fill('27ABCDE1234F1Z5');
      await page.locator('#field-vat_rate').fill('18');
    }
    await page.getByRole('button',{name:'Create my workspace',exact:true}).click();
    await page.waitForFunction(()=>!document.querySelector('#editor').open);
    return page.evaluate(()=>S.bid);
  }
  const retail=await createBusiness('retail','Fictional Pune Parts','IN');
  check((await api('state?business='+retail)).business.currency==='INR','India onboarding did not select INR');
  await nav('customers');await formSave('customers',{name:'Fictional Aarav Fleet',phone:'9000000001',address:'Test Lane, Pune',state_code:'27',tags:'Fleet, Repeat',preferred_language:'Hindi',discount_percent:'10',payment_terms_days:'15'});
  let state=await api('state?business='+retail);const customer=state.records.customers[0];
  check(customer.tags.includes('Fleet')&&customer.preferred_language==='Hindi','Customer preferences did not persist');
  await nav('stock');await formSave('stock',{name:'Fictional air filter',sku:'FILTER-TEST',barcode:'123456789TEST',opening_qty:'5',cost:'400',rate:'1000',category_label:'Filters',tax_rate:'18',hsn_sac:'8421',cess_rate:'0'});
  state=await api('state?business='+retail);const stock=state.records.stock[0];
  await nav('today');await page.getByRole('button',{name:'Quick bill',exact:true}).click();
  await page.locator('#field-checkout_customer').selectOption(customer.id);
  await page.getByLabel('Search item, SKU or scan barcode').fill('123456789TEST');
  await page.getByLabel('Search item, SKU or scan barcode').press('Enter');
  await page.locator('[data-cart-qty="0"]').fill('2');await page.locator('[data-cart-qty="0"]').press('Tab');
  check((await page.locator('#checkout-terms').textContent()).includes('10% agreed discount'),'Quick billing ignored customer terms');
  await page.screenshot({path:out+'/quick-bill-desktop.png',fullPage:true});
  await page.getByRole('button',{name:'Review bill',exact:true}).click();
  check(await page.locator('#field-discount_percent').inputValue()==='10','Customer discount missing from invoice');
  check(await page.locator('[data-col="hsn_sac"]').inputValue()==='8421','Catalogue HSN missing from invoice');
  await page.locator('#document-totals .grand').getByText('2,124.00',{exact:false}).waitFor();
  await page.locator('[form="document-form"]').click();
  await page.getByRole('button',{name:'Issue & retain invoice',exact:true}).click();await page.locator('#confirm-action').click();
  await page.getByRole('button',{name:'Return / credit items',exact:false}).waitFor();
  state=await api('state?business='+retail);let invoice=state.records.invoices[0];
  check(invoice._totals.total===2124&&invoice._totals.tax_components.CGST===162,'Issued GST totals incorrect');
  check(state.records.stock[0]._quantity===3,'Quick sale did not consume stock');
  const printed=await page.request.get(`${new URL(page.url()).origin}/print?business=${retail}&kind=invoices&id=${invoice.id}`);
  check(printed.ok()&&(await printed.text()).includes('HSN / SAC: 8421'),'Indian print does not retain HSN');
  await page.getByRole('button',{name:'Return / credit items',exact:false}).click();
  await page.locator('#return-0').fill('1');await page.locator('[data-restock-index="0"]').check();await page.locator('#field-reason').fill('One unopened filter returned');
  await page.getByRole('button',{name:'Post credit',exact:true}).click();
  await page.getByRole('heading',{name:'Credit note',exact:true}).waitFor();
  state=await api('state?business='+retail);
  check(state.records.credits[0].amount===1062&&state.records.stock[0]._quantity===4,'Return did not reconcile credit and stock');
  await close();await nav('customers');await page.getByRole('button',{name:'Outstanding',exact:false}).click();
  await page.locator(`[data-action="open"][data-id="${customer.id}"]`).first().click();
  await page.getByRole('heading',{name:'Relationship timeline'}).waitFor();
  check((await page.locator('.client-identity').textContent()).includes('Hindi'),'Customer hub lost contact preference');
  await page.screenshot({path:out+'/client-hub-desktop.png',fullPage:true});await close();
  await nav('settings');await page.getByRole('button',{name:'Personalise this business',exact:true}).click();
  await page.locator('#field-workspace_name').fill('Pune Parts Desk');await page.locator('#field-brand_color').selectOption('blue');
  await page.getByRole('button',{name:'Add field',exact:false}).click();
  await page.getByLabel('Field area',{exact:true}).selectOption('customers');await page.getByLabel('Field label',{exact:true}).fill('Fleet contract');await page.getByLabel('Stable field key',{exact:true}).fill('fleet_contract');
  await page.getByRole('button',{name:'Save personalisation',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('#editor').open);
  check(await page.evaluate(()=>document.documentElement.dataset.brand)==='blue','Business accent was not applied');
  await nav('customers');await page.getByRole('button',{name:'All customers',exact:false}).click();await page.locator(`[data-action="open"][data-id="${customer.id}"]`).first().click();await page.getByRole('button',{name:'Edit',exact:true}).click();
  await page.getByLabel('Fleet contract',{exact:true}).fill('FLEET-TEST-01');await page.locator('[form="record-form"]').click();await page.waitForFunction(()=>!document.querySelector('#editor').open);
  state=await api('state?business='+retail);check(state.records.customers[0].custom_fields.fleet_contract==='FLEET-TEST-01','Business custom field did not persist');
  await nav('today');await page.keyboard.press('Control+k');await page.getByLabel('Search commands and records',{exact:true}).fill('Fictional Aarav');await page.locator('#command-results button').first().click();
  check(await page.getByRole('heading',{name:'Relationship timeline'}).count()===1,'Command search did not open customer');await close();
  await page.setViewportSize({width:390,height:844});
  check(await page.locator('.mobile-tabs').isVisible(),'Mobile quick navigation missing');
  check(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1),'India dashboard overflows phone');
  await page.screenshot({path:out+'/india-dashboard-phone.png',fullPage:true});
  await page.getByRole('button',{name:'Quick bill',exact:true}).click();await page.screenshot({path:out+'/quick-bill-phone.png',fullPage:true});
  check(await page.locator('.checkout').evaluate(x=>x.scrollWidth<=window.innerWidth),'Phone quick billing overflows');await close();await page.setViewportSize({width:1440,height:1100});
  const service=await createBusiness('service','Fictional Repair Visits');
  check(await page.getByRole('heading',{name:'Upcoming visits',exact:true}).count()===1,'Service profile has no appointment workspace');
  check((await page.locator('.sidebar').textContent()).includes('Service work'),'Service vocabulary missing');
  await page.screenshot({path:out+'/service-workspace-desktop.png',fullPage:true});
  const garage=await createBusiness('garage','Fictional Collision Works');
  await nav('customers');await formSave('customers',{name:'Fictional Garage Client'});state=await api('state?business='+garage);
  await nav('workshop');await formSave('jobs',{name:'Fictional bumper repair',customer_id:state.records.customers[0].id});
  state=await api('state?business='+garage);
  check(state.records.jobs[0].tasks.length>=4,'Garage checklist was not applied');
  await nav('today');check(await page.getByRole('heading',{name:'Workshop queue',exact:true}).count()===1,'Garage profile has no workshop queue');
  await page.screenshot({path:out+'/garage-workspace-desktop.png',fullPage:true});
  const all=await api('businesses');check(all.length===4,'Four separate sector businesses were not created');
  check(!state.records.invoices.length&&!state.records.stock.length,'Indian retail data leaked into garage workspace');
  check((await page.locator('.sidebar').textContent()).includes('No charges'),'Free pilot status missing');
}
