export async function verifyStudio({page,api,check,nav,close,formSave,out,fs}){
 await page.setViewportSize({width:1440,height:1100});
 await nav('settings');await page.getByRole('button',{name:'Guided configuration',exact:false}).click();
 await page.getByLabel('Name your customers know',{exact:true}).fill('Collision Craft');
 await page.getByLabel('Installed app name (up to 24 characters)').fill('Craft');
 await page.locator('#guide-colour').fill('#2563eb');
 await page.getByRole('button',{name:'Continue',exact:true}).click();
 await page.getByLabel('Who approves scope or extra work?').fill('Owner approves every supplement with the customer.');
 await page.getByRole('button',{name:'Continue',exact:true}).click();
 await page.getByLabel('Which clients do you serve most?').fill('Local owners and small fleets');
 await page.getByRole('button',{name:'Continue',exact:true}).click();
 await page.getByLabel('Payment instructions shown on documents').fill('Use your bill number as payment reference.');
 await page.getByLabel('Business footer on documents').fill('Collision Craft · Thank you');
 await page.getByLabel('Enforce customer credit limits on new bills').check();
 await page.getByRole('button',{name:'Continue',exact:true}).click();
 await page.getByLabel('How do you agree pay and incentives?').fill('Reviewed attendance, agreed salary and approved collection-based incentives.');
 await page.getByRole('button',{name:'Continue',exact:true}).click();
 await page.getByLabel('Which tools and paper registers are you replacing?').fill('CSV exports and a cash register');
 await page.screenshot({path:out+'/business-configuration-desktop.png',fullPage:true});
 await page.getByRole('button',{name:'Save business configuration',exact:true}).click();
 await page.waitForFunction(()=>!document.querySelector('#editor').open);
 let state=await api('state?business='+await page.evaluate(()=>S.bid));const bid=state.business.id;
 check(state.business.trading_name==='Collision Craft'&&state.business.operating_rules.credit_limit_enforced,'Guided configuration did not retain business rules');
 check(state.business.discovery.approval_process.includes('supplement'),'Detailed configuration answers were not saved');
 check((await page.title()).startsWith('Collision Craft'),'Browser title does not belong to the business');
 check((await page.locator('.sidebar .brand').textContent()).includes('Collision Craft'),'Sidebar does not carry trading name');
 const manifest=await page.evaluate(async()=>await (await fetch(document.querySelector('link[rel=manifest]').href)).json());
 check(manifest.name==='Collision Craft'&&manifest.start_url.includes(bid),'Installed app identity is generic');
 await page.getByRole('button',{name:'Move your existing records',exact:false}).click();
 await page.locator('#csv-file').setInputFiles({name:'reviewed-customers.csv',mimeType:'text/csv',buffer:Buffer.from('name,phone,address,credit_limit\r\n"Migrated Fleet",9000000091,"Pune, test lane",20000\r\n')});
 await page.locator('[data-csv-field=name]').waitFor();await page.getByRole('button',{name:'Preview & validate',exact:true}).click();
 await page.getByText('Nothing has been saved.',{exact:true}).waitFor();
 state=await api('state?business='+bid);check(!state.records.customers.some(x=>x.name==='Migrated Fleet'),'CSV preview wrote records');
 await page.getByRole('button',{name:'Import reviewed rows',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('#editor').open);
 state=await api('state?business='+bid);const customer=state.records.customers.find(x=>x.name==='Migrated Fleet');
 check(customer?.address==='Pune, test lane'&&customer.credit_limit===20000,'Quoted CSV fields or numeric mapping failed');
 await nav('stock');await formSave('stock',{name:'Counted filter',sku:'COUNT-1',opening_qty:'5',cost:'100',rate:'300'});
 state=await api('state?business='+bid);const stock=state.records.stock.find(x=>x.sku==='COUNT-1');
 await page.getByRole('button',{name:'Count stock',exact:false}).click();
 await page.getByLabel('Count Counted filter',{exact:true}).check();await page.getByLabel('Physical quantity of Counted filter').fill('3');await page.getByLabel('Reason / count reference').fill('Reviewed shelf count');
 await page.getByRole('button',{name:'Post count adjustments',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('#editor').open);
 state=await api('state?business='+bid);check(state.records.stock.find(x=>x.id===stock.id)._quantity===3,'Physical count did not create stock adjustment');
 await nav('customers');await page.locator(`[data-action=open][data-kind=customers][data-id="${customer.id}"]`).first().click();
 await page.getByRole('button',{name:'Agreed prices',exact:true}).click();await page.getByRole('button',{name:'Add agreed price',exact:false}).click();
 await page.getByLabel('Catalogue item').selectOption(stock.id);await page.locator('[data-agree-qty]').fill('2');await page.locator('[data-agree-rate]').fill('250');
 await page.getByRole('button',{name:'Save agreed prices',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('#editor').open);
 await nav('today');await page.getByRole('button',{name:'Quick bill',exact:true}).click();await page.locator('#field-checkout_customer').selectOption(customer.id);
 await page.locator(`[data-catalogue-id="${stock.id}"]`).click();await page.locator('[data-cart-qty="0"]').fill('2');await page.locator('[data-cart-qty="0"]').press('Tab');
 check((await page.locator('#checkout-cart').textContent()).includes('250.00'),'Customer quantity tier was not applied');await close();
 await nav('money');await page.locator('[data-action=tab][data-kind=opening_balances]').click();
 await formSave('opening_balances',{customer_id:customer.id,amount:'500',date:state.today,source_reference:'Approved ledger 1',reconciled:true});
 state=await api('state?business='+bid);const opening=state.records.opening_balances[0];await page.locator(`[data-action=open][data-kind=opening_balances][data-id="${opening.id}"]`).first().click();
 await page.getByRole('button',{name:'Record receipt',exact:true}).click();await page.locator('#field-amount').fill('200');
 await page.locator('[form=record-form][type=submit]').click();await page.waitForFunction(()=>!document.querySelector('#editor').open);
 state=await api('state?business='+bid);check(state.records.opening_balances[0]._balance===300,'Opening receipt did not clear balance');
 await nav('customers');await page.locator(`[data-action=open][data-kind=customers][data-id="${customer.id}"]`).first().click();await page.getByRole('button',{name:'Account statement',exact:false}).click();
 check((await page.locator('.statement-summary').textContent()).includes('300.00'),'Customer statement is not reconciled');await page.screenshot({path:out+'/customer-statement-desktop.png',fullPage:true});await close();
 await nav('money');await page.locator('[data-action=tab][data-kind=cash_closures]').click();await formSave('cash_closures',{date:state.today,opening_float:'100',counted_cash:'300',notes:'Drawer counted against recorded receipts'});
 state=await api('state?business='+bid);check(state.records.cash_closures[0].variance===0,'Cash count does not reconcile recorded cash');
 await nav('workshop');const job=state.records.jobs[0];await page.locator(`[data-action=open][data-kind=jobs][data-id="${job.id}"]`).first().click();await page.getByRole('button',{name:'Inspection',exact:false}).click();
 await page.locator('[data-inspect-condition]').first().selectOption('urgent');await page.locator('[data-inspect-notes]').first().fill('Original condition recorded');
 await page.getByRole('button',{name:'Save inspection',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('#editor').open);
 state=await api('state?business='+bid);check(state.records.jobs[0].inspection[0].condition==='urgent','Inspection findings were not retained');
 // Exercise rendering against a large snapshot without inventing a production scale claim.
 const performance=await page.evaluate(()=>{
  const source=S.state;const original=source.records.customers;const synthetic=Array.from({length:2000},(_,i)=>({...original[0],id:'bench-'+i,name:'Benchmark client '+i}));
  S.state={...source,records:{...source.records,customers:synthetic}};S.page='customers';S.tab='customers';S.query='';S.listQuery='';S.customerSegment='all';
  const durations=[];for(let i=0;i<15;i++){const start=performance.now();renderContent();durations.push(performance.now()-start);}durations.sort((a,b)=>a-b);const result={measurement:'Synchronous DOM rendering; excludes paint, network and database',records:2000,visible_rows:document.querySelectorAll('#list-data tbody tr').length,p50_ms:durations[7],p95_ms:durations[14]};
  S.state=source;S.listSignature='';renderContent();return result;
 });
 check(performance.visible_rows===50,'Large customer lists are not paginated');check(performance.p95_ms<1500,'Customer rendering exceeded the conservative CI regression budget');
 await fs.writeFile(out+'/render-performance.json',JSON.stringify(performance,null,2));
 const parsed=await page.evaluate(()=>parseCSV('name,notes\r\n"Test","Line one\nLine two and ""quotes"""\r\n'));
 check(parsed.rows[0][1]==='Line one\nLine two and "quotes"','CSV parser loses embedded lines or quotes');
 await nav('today');await page.screenshot({path:out+'/business-owned-dashboard-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:out+'/business-owned-dashboard-phone.png',fullPage:true});
 check(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1),'Configured business dashboard overflows phone');
 await nav('settings');await page.getByRole('button',{name:'Guided configuration',exact:false}).click();
 check(await page.locator('#guide-form').evaluate(x=>x.scrollWidth<=window.innerWidth),'Configuration overflows phone');await page.screenshot({path:out+'/business-configuration-phone.png',fullPage:true});await close();
 await page.setViewportSize({width:1440,height:1100});await nav('today');
}
